### ISSUE TITLE
Add QR Scanner to the Home Screen

### ISSUE THREAD

**Issue by amanjagdev** [amanjagdev/salyd#1]
A QR code scanner is to be added instead of the current green view box in the Home Screen.
Home Screen is the main dashboard from where a person can scan the QR code present on the table of the restaurant to create a room inside the app.

QR Code Scanner should be able to do the following :
- Scan the QR code on the table and then add it to the local state of the table code.
- A rescan button should appear after the code has been scanned once.
- It must fit with the current styling of the application

Note: Expo is used for the project, so don't eject the project to use any third party non-expo supported library.
Stick to widely available expo compatible libraries

**Comment by asi309** [comment]
I can work on this.

**Comment by amanjagdev** [comment]
> I can work on this.

Great... I hope you understand what feature is needed to be added. Please do the following and make a pull request for the same. Feel free to ping me if you encounter any problem while understanding the project structure.
Shall I assign you to this issue?

**Comment by asi309** [comment]
Yes, please assign me
