### ISSUE TITLE
Implementation of UI Screens

### ISSUE THREAD

**Issue by kg-kartik** [amanjagdev/salyd#2]
UI for Forgot Password Screen and New Password Screen needs to be implemented 
In Forgot Password Screen,
https://github.com/amanjagdev/salyd/blob/master/screens/ForgotPassword.js. 
Here, a text input and Button component (which is to be used as reusable component present in components folder) needs to be added.
On clicking the button, it should take to a new screen for entering new password.
Add two text input fields(password and confirm password) and a button (same as mentioned above). 
The navigation stack needs to be taken in care and stack for the New Password Screen needs to be added accordingly.

**Comment by jabo-bernardo** [comment]
I would like to work on this, Can you assign me?

**Comment by kg-kartik** [comment]
Yea sure, I guess you would have got more of the idea how to do. So, I am assigning you the issue,
for further doubts you can ask here!

**Comment by adrikagupta** [comment]
Hey! I am planning to work on this. Can you assign it to me?

**Comment by kg-kartik** [comment]
Yes, sure. So, I am assigning you the issue , feel free to ping in case of any doubt!

**Comment by adrikagupta** [comment]
Thanks. Yes, sure.
