### ISSUE TITLE
Add validation in login and signup screens

### ISSUE THREAD

**Issue by kg-kartik** [amanjagdev/salyd#3]
Validation in login and signup screens needs to be added.
Either validation can be done on client side(on same repo) or express validators can be added in server repo
https://github.com/kg-kartik/salyd-server

**Comment by develper** [comment]
May I work on this issue, please?

**Comment by kg-kartik** [comment]
Yea sure, I guess you would have got more of the idea how to do. So, I am assigning you the issue,
for further doubts you can ask here!

**Comment by Gautam-Arora24** [comment]
Can I solve this issue?

**Comment by develper** [comment]
@kg-kartik , I am planning to add validation on the server-side using express.
Let me know if you have any concerns.

**Comment by kg-kartik** [comment]
> @kg-kartik , I am planning to add validation on the server-side using express.
> Let me know if you have any concerns.

Cool no problem ! I am assigning you the issue!

**Comment by kg-kartik** [comment]
> Can I solve this issue with the help of Express-validators?

Sorry @Gautam-Arora24 , the issue has been already assigned, I have opened one more issue in the salyd-server repo https://github.com/kg-kartik/salyd-server 
You can check it out!

**Comment by develper** [comment]
@kg-kartik Validation is already in place at server-side. So should I replace them with "express - validators"?
Please resolve my confusion, if I am missing something here.

**Comment by kg-kartik** [comment]
> @kg-kartik Validation is already in place at server-side. So should I replace them with "express - validators"?
> Please resolve my confusion, if I am missing something here.

No, validation is not there as of now. There is only an email validation that too using regex . Yes, express validators needs to be implemented .
